import {useState,useEffect,useRef} from 'react';
import {ArrowUpRight,ArrowDown,ArrowLeft,ArrowRight,Search,X,Plus} from '../portal/icons.jsx';
import {regions,cities,projects,news,regionById,cityById,regionPath,cityPath,projectHref,media,dateText,normalize,regionMood} from '../portal/data.js';
import {siteHref} from '../site.js';
import {asset} from '../data.js';
import {parentTerritory,territoryName} from '../content/territory-model.js';
import {NewsLink} from '../portal/NewsModal.jsx';
import {useQueryState} from '../portal/interactions.jsx';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
const pad=n=>String(n).padStart(2,'0');
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
export const Picture=({src,alt='',eager=false,...props})=><img src={media(src)} alt={alt} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':undefined} decoding="async" {...props}/>;
export const HLink=({href,children,className=''})=><a className={`s-link ${className}`} href={href}><span>{children}</span><span className="s-link-arrow"><ArrowUpRight size={19}/></span></a>;
export const Label=({number,children})=><div className="s-label"><span>{number}</span><span>{children}</span></div>;
export const Heading=({number,label,title,href,link})=><div className="s-heading"><Label number={number}>{label}</Label><h2>{title}</h2>{href&&<HLink href={href}>{link}</HLink>}</div>;
// Every image is an uninterrupted surface; the architectural edge belongs to the layout.
export function Aperture({src='home-hero.webp',className='',eager=false}){return <div className={`s-panorama ${className}`}><Picture src={src} eager={eager}/></div>;}

export function HorizonMotion(){
 useEffect(()=>{const mm=gsap.matchMedia();
 mm.add('(prefers-reduced-motion: no-preference)',()=>{
  const intro=document.querySelector('.s-intro');
  if(intro){
   gsap.fromTo('.s-intro-title span',{yPercent:110},{yPercent:0,duration:1.15,ease:'power3.out',delay:.1});
   gsap.fromTo('.s-intro-photo img',{scale:1.08},{scale:1,duration:2,ease:'power2.out'});
   if(matchMedia('(min-width: 901px)').matches){
    const opening=gsap.timeline({scrollTrigger:{trigger:intro,start:'top top',end:'bottom bottom',scrub:.6}});
    opening.to('.s-intro-photo',{top:0,ease:'none'},0)
      .to('.s-intro-white',{yPercent:-100,ease:'none'},0)
      .to('.s-intro-title-panel',{y:()=>-window.innerHeight*.46,ease:'none'},0)
      .to('.s-intro-caption',{top:'18%',ease:'none'},0);
   }
  }
  gsap.utils.toArray('.v3-site [data-s-reveal]').forEach(el=>gsap.fromTo(el,{y:45},{y:0,duration:1.1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 94%',once:true}}));
  gsap.utils.toArray('.v3-site .s-manifesto-word').forEach((el,i)=>gsap.fromTo(el,{opacity:.22},{opacity:1,ease:'none',scrollTrigger:{trigger:'.s-manifesto',start:`top+=${i*18} 75%`,end:`top+=${i*18+200} 50%`,scrub:true}}));
  gsap.utils.toArray('.v3-site [data-s-photo]').forEach(el=>gsap.fromTo(el,{clipPath:'inset(12% 0 0 0)'},{clipPath:'inset(0% 0 0 0)',ease:'none',scrollTrigger:{trigger:el,start:'top 95%',end:'top 40%',scrub:.5}}));
 });
 const refresh=()=>ScrollTrigger.refresh();window.addEventListener('load',refresh);document.fonts?.ready.then(refresh);
 return()=>{mm.revert();window.removeEventListener('load',refresh);};},[]);return null;
}

function Intro(){return <section className="s-intro" aria-labelledby="home-title"><div className="s-intro-stage">
 <div className="s-intro-white"><span className="s-intro-eyebrow">Новый облик Дальнего Востока</span><span className="s-intro-edition">Мастер-планы развития / 2026</span></div>
 <div className="s-intro-photo" data-header-tone="dark"><Picture src="home-hero.webp" eager/><div className="s-intro-photo-shade"/></div>
 <div className="s-intro-title-panel"><h1 id="home-title" className="s-intro-title"><span>25 городов</span></h1><a href="#idea" className="s-down" aria-label="Узнать о проекте"><ArrowDown size={20}/></a></div>
 <div className="s-intro-caption"><p>Место, где<br/>будущее становится<br/>настоящим.</p><span>Владивосток / Русский мост</span></div>
 <div className="s-intro-bottom"><span>11 регионов — одна большая перемена</span><a href={siteHref('regions')}>Выбрать свою территорию<ArrowUpRight size={22}/></a></div>
 </div></section>;}

const manifesto='Мы меняем облик городов, чтобы менять жизнь. Создаём места для новых идей, встреч и возможностей. Сохраняем характер Дальнего Востока. Открываем его будущее.';
function Manifesto(){return <section className="s-manifesto" id="idea" data-header-tone="dark"><div className="s-shell"><Label number="01">Новая среда жизни</Label><h2 className="s-manifesto-text">{manifesto.split(' ').map((word,i)=><span className="s-manifesto-word" key={i}>{word} </span>)}</h2><div className="s-manifesto-bottom"><span>От стратегии развития<br/>к повседневной жизни</span><p>Мастер-планы объединяют экономику, инфраструктуру и городскую среду. В центре этой работы — человек и его возможности.</p><HLink href={siteHref('about')}>О проекте</HLink></div></div></section>;}

const facts=[{value:'25',unit:'городов',title:'Города с новым будущим',text:'Единая программа развития. Индивидуальный мастер-план для каждой территории.',image:'home-hero.webp',href:siteHref('regions')},{value:'11',unit:'регионов',title:'От Байкала до Тихого океана',text:'Разная природа, культура и экономика. Развитие с уважением к характеру каждого места.',image:'home-region-3.webp',href:siteHref('regions')},{value:'4 млн+',unit:'жителей',title:'Перемены для каждого',text:'Новые возможности для работы, учёбы, отдыха и жизни в своём городе.',image:'editorial/visual-waterfront.webp',href:siteHref('projects')}];
function Facts(){const[index,setIndex]=useState(0);const f=facts[index];return <section className="s-facts s-shell"><div className="s-facts-top"><Label number="02">Масштаб перемен</Label><span>За цифрами — люди и места</span></div><div className="s-facts-tabs" role="group" aria-label="Масштаб проекта">{facts.map((item,i)=><button key={item.value} aria-pressed={index===i} onClick={()=>setIndex(i)}><strong>{item.value}</strong><span>{item.unit}<Plus size={20}/></span></button>)}</div><div className="s-fact-detail" key={index}><Picture src={f.image}/><div aria-live="polite"><h3>{f.title}</h3><p>{f.text}</p><HLink href={f.href}>Узнать больше</HLink></div><span className="s-fact-index">{pad(index+1)} / 03</span></div></section>;}

export function HorizonExplorer({items=regions}){
 const[active,setActive]=useState(items[0]?.id);const r=items.find(x=>x.id===active)||items[0];
 if(!r)return <p className="s-empty">Ничего не найдено. Попробуйте другой запрос.</p>;
 return <div className="s-explorer e-region-explorer"><div className="s-region-preview"><Picture key={r.id} src={`home-region-${r.index}.webp`} alt={r.name}/><div className="s-region-preview-content" key={`text-${r.id}`} aria-live="polite"><span>{pad(r.index)} / 11</span><h3>{r.name}</h3><p>{regionMood[r.id]}</p><HLink href={siteHref(regionPath(r))}>Исследовать регион</HLink></div></div><div className="s-region-list" role="group" aria-label="Выбрать регион">{items.map(item=><button key={item.id} aria-pressed={r.id===item.id} onClick={()=>setActive(item.id)} onMouseEnter={()=>{if(matchMedia('(hover:hover)').matches)setActive(item.id);}} onFocus={()=>setActive(item.id)}><span>{pad(item.index)}</span><span>{item.name}</span><ArrowUpRight size={19}/></button>)}</div></div>;
}

const life=[{word:'Жить',image:'housing',title:'Новый взгляд\nна привычное.',text:'Современные кварталы. Продуманные дворы. Всё, что нужно для жизни, — рядом.',href:siteHref('dvkvartal'),link:'Дальневосточный квартал'},{word:'Учиться',image:'school',title:'Пространство\nдля большого.',text:'Школы, детские сады и образовательные пространства для нового поколения.',href:siteHref('projects','?q=школ'),link:'Проекты образования'},{word:'Отдыхать',image:'waterfront',title:'Время\nдля себя.',text:'Набережные, парки и прогулочные маршруты. Места для встреч и новых впечатлений.',href:siteHref('projects','?q=набережн'),link:'Проекты набережных'}];
function Life(){const[index,setIndex]=useState(0);const ref=useRef(null);const trigger=useRef(null);
 useEffect(()=>{const mm=gsap.matchMedia();mm.add('(min-width: 901px) and (prefers-reduced-motion: no-preference)',()=>{trigger.current=ScrollTrigger.create({trigger:ref.current,start:'top top',end:'bottom bottom',onUpdate:s=>setIndex(Math.min(2,Math.floor(s.progress*3)))});return()=>{trigger.current=null;};});return()=>mm.revert();},[]);
 const choose=i=>{setIndex(i);const t=trigger.current;if(t)window.scrollTo({top:t.start+(t.end-t.start)*(i+.4)/3,behavior:'smooth'});};
 return <section className="s-life" ref={ref} id="life" data-header-tone="dark"><div className="s-life-sticky"><div className="s-life-images">{life.map((item,i)=><Picture key={item.word} src={`editorial/visual-${item.image}.webp`} className={index===i?'is-active':''}/>)}</div><div className="s-life-top"><Label number="04">Город — это жизнь</Label><span>Образ городской среды</span></div><div className="s-life-title" key={index} aria-live="polite"><span>0{index+1} / 03</span><h2>{life[index].title}</h2></div><div className="s-life-bottom"><div role="group" aria-label="Жизнь в городе" className="s-life-tabs">{life.map((item,i)=><button key={item.word} aria-pressed={index===i} onClick={()=>choose(i)}><span>0{i+1}</span>{item.word}<ArrowUpRight size={22}/></button>)}</div><div className="s-life-copy" key={`copy-${index}`}><p>{life[index].text}</p><HLink href={life[index].href}>{life[index].link}</HLink></div></div></div></section>;
}

function ProjectsRail(){const rail=useRef(null);const picks=['vladivostok','ulan-ude','petropavlovsk-kamchatsky','khabarovsk','yuzhno-sakhalinsk'].map(id=>projects.find(p=>p.city===id&&p.hasSourceImages)).filter(Boolean);const[at,setAt]=useState(0);return <section className="s-projects" id="projects"><div className="s-shell"><Heading number="05" label="Места будущего" title={<>Идеи обретают<br/>форму.</>} href={siteHref('projects')} link={`Все ${projects.length} проектов`}/><div className="s-rail-controls"><span>Архитектура перемен</span><div><button aria-label="Предыдущие проекты" disabled={at===0} onClick={()=>rail.current.scrollBy({left:-rail.current.clientWidth*.68,behavior:reduced()?'instant':'smooth'})}><ArrowLeft/></button><button aria-label="Следующие проекты" disabled={at===2} onClick={()=>rail.current.scrollBy({left:rail.current.clientWidth*.68,behavior:reduced()?'instant':'smooth'})}><ArrowRight/></button></div></div></div><div className="s-project-rail" ref={rail} tabIndex="0" role="region" aria-label="Избранные проекты" onScroll={e=>{const el=e.currentTarget;setAt(el.scrollLeft<5?0:el.scrollLeft+el.clientWidth>=el.scrollWidth-5?2:1);}}>{picks.map((p,i)=><a className="s-project-tile" key={p.id} href={projectHref(p)}><div className="s-project-photo"><Picture src={p.images[0]} alt={p.title}/><span className="s-project-arrow"><ArrowUpRight size={28}/></span></div><div className="s-project-meta"><span>{pad(i+1)} / {cityById[p.city]?.name}</span><span>Мастер-план</span></div><h3>{p.title}</h3></a>)}</div></section>;}

export function HorizonHome(){return <div className="s-home"><Intro/><Manifesto/><Facts/><section className="s-geography s-shell" id="geography"><Heading number="03" label="География проекта" title={<>У каждого места —<br/>свой характер.</>} href={siteHref('regions')} link="Все территории"/><HorizonExplorer/></section><Life/><ProjectsRail/><section className="s-news s-shell" id="news"><Heading number="06" label="Дневник перемен" title="Уже происходит." href={siteHref('news')} link="Все новости"/><div className="s-news-list">{news.slice(0,3).map((n,i)=><NewsLink key={n.id} post={n} className="s-news-row"><span>{pad(i+1)}</span><Picture src={n.image}/><div><time dateTime={n.date}>{dateText(n.date)}</time><h3>{n.title}</h3></div><ArrowUpRight size={28}/></NewsLink>)}</div></section><a className="s-map-callout" href={siteHref('map')} data-header-tone="dark"><span>Следующая точка — ваша</span><strong>Откройте<br/>новый Восток.</strong><span className="s-map-circle"><ArrowUpRight strokeWidth={1}/></span><span className="s-map-bottom">Перейти к карте проектов <ArrowRight size={22}/></span></a></div>;}

export function HorizonPageHero({image,title,eyebrow,crumbs=[],children,compact=false,illustration=false}){return <section className={`s-page-hero ${image?'s-page-hero-image':''} ${compact?'s-page-compact':''}`}><div className="s-shell"><div className="s-page-meta"><a href={siteHref()}>Главная</a><span>/</span><span>{crumbs.at(-1)?.[0]||eyebrow}</span><span className="s-page-meta-end">25 городов / Новый облик</span></div><div className="s-page-hero-content"><Label number="↗">{eyebrow}</Label><h1>{title}</h1>{children&&<div className="s-page-description">{children}</div>}</div></div>{image&&<div className="s-page-art" data-s-photo><Picture src={image} eager/>{illustration&&<small>Иллюстрация</small>}</div>}</section>;}

export function HorizonDirectory(){
 const[q,setQ]=useQueryState('q');const[view,setView]=useQueryState('view','regions');const cityView=view==='cities';
 const regionMatches=regions.filter(r=>normalize(r.name+' '+r.cities.map(id=>cityById[id].name).join(' ')).includes(normalize(q)));
 const cityMatches=cities.filter(c=>parentTerritory(c.id)===c.id).filter(c=>normalize(territoryName(c)+' '+regionById[c.region]?.name+' '+cities.filter(m=>parentTerritory(m.id)===c.id).map(m=>m.name).join(' ')).includes(normalize(q)));
 const href=c=>{const member=q.trim()?cities.find(m=>parentTerritory(m.id)===c.id&&normalize(m.name).includes(normalize(q))):null;return siteHref(cityPath(c),member&&member.id!==c.id?`?city=${member.id}#regions`:'');};
 return <div className="s-directory"><HorizonPageHero title={<>География<br/>перемен.</>} eyebrow="От Байкала до Тихого океана" crumbs={[["Регионы"]]} compact/><div className="s-shell"><div className="s-directory-tools"><div role="group" aria-label="Показать территории"><button aria-pressed={!cityView} onClick={()=>setView('regions')}>Регионы <sup>11</sup></button><button aria-pressed={cityView} onClick={()=>setView('cities')}>Города и агломерации <sup>{cities.filter(c=>parentTerritory(c.id)===c.id).length}</sup></button></div><label className="s-search"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Регион или город" aria-label="Найти регион или город"/>{q&&<button onClick={()=>setQ('')} aria-label="Очистить поиск"><X size={20}/></button>}</label></div><div className="s-result-count" aria-live="polite">{cityView?'Территорий':'Регионов'}: {cityView?cityMatches.length:regionMatches.length}</div>{cityView?<div className="s-city-grid">{cityMatches.map((c,i)=><a key={c.id} href={href(c)}><div><Picture src={c.image}/><span>{pad(i+1)}<ArrowUpRight size={24}/></span></div><small>{regionById[c.region].name}</small><h2>{territoryName(c)}</h2></a>)}</div>:<HorizonExplorer items={regionMatches}/>} {cityView&&!cityMatches.length&&<p className="s-empty">Ничего не найдено. Попробуйте другой запрос.</p>}</div></div>;
}

const aboutSteps=[{name:'Услышать',title:'Начать с человека.',text:'Мастер-планы создаются с учётом мнения жителей. Их потребности помогают определить общие цели развития и приоритеты городской среды.',image:'editorial/visual-waterfront.webp'},{name:'Связать',title:'Увидеть город целиком.',text:'Жильё, работа, образование, транспорт и отдых связаны между собой. Мастер-план объединяет их в общую стратегию пространственного и экономического развития.',image:'masterplan-editorial-v1.webp'},{name:'Создать',title:'Превратить идеи в места.',text:'Стратегия становится набором конкретных проектов. На портале можно изучить их параметры и расположение в мастер-планах городов.',image:'editorial/visual-school.webp'}];
export function HorizonAbout(){const[index,setIndex]=useState(0);const s=aboutSteps[index];return <div className="s-about"><HorizonPageHero image="hero-primorye.webp" title={<>Новый облик.<br/>Новые возможности.</>} eyebrow="О проекте «25 городов»" crumbs={[["О проекте"]]}><p>Развитие городов Дальнего Востока.<br/>С вниманием к месту и человеку.</p><HLink href="#approach">Как это работает</HLink></HorizonPageHero><Manifesto/><section className="s-approach s-shell" id="approach"><Heading number="02" label="От замысла к переменам" title={<>Как устроен<br/>мастер-план.</>}/><div className="s-approach-layout"><div className="s-approach-tabs" role="group" aria-label="Этапы мастер-плана">{aboutSteps.map((a,i)=><button aria-pressed={index===i} onClick={()=>setIndex(i)} key={a.name}><span>{pad(i+1)}</span>{a.name}<ArrowUpRight/></button>)}</div><div className="s-approach-body" key={index}><Picture src={s.image}/><div aria-live="polite"><h3>{s.title}</h3><p>{s.text}</p><HLink href={siteHref('projects')}>Посмотреть проекты</HLink></div></div></div></section><Facts/><section className="s-shell s-about-faq"><Heading number="03" label="По существу" title="Что важно знать."/><div>{[['Чем мастер-план отличается от генерального плана?','Генеральный план отвечает на вопрос, что и где будет построено. Мастер-план объясняет, как и зачем развивается город: в контексте социальных, экономических и пространственных задач. Он описывает управленческие механизмы и источники финансирования.'],['Для кого создаются мастер-планы?','Мастер-план — публичный документ для жителей, бизнеса и власти. Он определяет общие принципы и стратегию развития города.'],['Где посмотреть проекты моего города?','Выберите регион, затем город или агломерацию. На странице территории доступны мастер-план, карта объектов и подробности проектов.']].map(([q,a],i)=><details key={q} name="about-questions"><summary><span>{pad(i+1)}</span><h3>{q}</h3><Plus/></summary><p>{a}</p></details>)}</div></section></div>;}

export function HorizonFooter(){return <footer className="s-footer"><div className="s-shell"><div className="s-footer-top"><Label number="25">Новый облик Дальнего Востока</Label><a href={siteHref('regions')}>Будущее<br/>начинается здесь.<ArrowUpRight strokeWidth={1}/></a></div><div className="s-footer-body"><div><a href={siteHref()}><img src={asset('logo-25-cities.svg')} alt="25 городов" width="150" height="36"/></a><p>Корпорация развития<br/>Дальнего Востока и Арктики</p><a href="tel:88007075558">8 (800) 707-55-58</a></div><nav aria-label="Разделы в подвале">{[['about','О проекте'],['regions','Регионы'],['projects','Проекты'],['dvkvartal','ДВ Квартал'],['news','Новости'],['map','Карта проектов']].map(([p,n])=><a key={p} href={siteHref(p)}>{n}</a>)}</nav><nav className="s-footer-regions" aria-label="Регионы в подвале">{regions.map(r=><a key={r.id} href={siteHref(regionPath(r))}>{r.name}</a>)}</nav></div><div className="s-footer-bottom"><span>© 2026 / 25 городов</span><a href={siteHref('sitemap')}>Карта сайта</a><a href="#top">Наверх ↑</a></div></div></footer>;}
