import {useState,useEffect,useRef} from 'react';
import {ArrowUpRight,ArrowDown,ArrowLeft,ArrowRight,Search,X,Plus} from '../portal/icons.jsx';
import {regions,cities,projects,news,regionById,cityById,regionPath,cityPath,projectHref,media,dateText,normalize,regionMood,regionShort} from '../portal/data.js';
import {siteHref} from '../site.js';
import {asset} from '../data.js';
import {parentTerritory,territoryName} from '../content/territory-model.js';
import {NewsLink} from '../portal/NewsModal.jsx';
import {useQueryState} from '../portal/interactions.jsx';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
const pad=n=>String(n).padStart(2,'0');
export const Picture=({src,alt='',eager=false,...props})=><img src={media(src)} alt={alt} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':undefined} decoding="async" {...props}/>;
export const HLink=({href,children,className=''})=><a className={`s-link ${className}`} href={href}><span>{children}</span><span className="s-link-arrow"><ArrowUpRight size={20}/></span></a>;
export const Label=({number,children})=><div className="s-label"><span>{number}</span><span>{children}</span></div>;
export const Heading=({number,label,title,href,link})=><div className="s-heading"><Label number={number}>{label}</Label><h2>{title}</h2>{href&&<HLink href={href}>{link}</HLink>}</div>;

// One photographic surface, divided into architectural planes. No rasterised UI.
export function Aperture({src='home-hero.webp',className='',eager=false}){
 const ref=useRef(null);
 const move=e=>{if(e.pointerType!=='mouse'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const b=ref.current.getBoundingClientRect();ref.current.style.setProperty('--mx',`${(e.clientX-b.left)/b.width-.5}`);ref.current.style.setProperty('--my',`${(e.clientY-b.top)/b.height-.5}`);};
 return <div ref={ref} className={`s-aperture ${className}`} onPointerMove={move} onPointerLeave={()=>{ref.current?.style.setProperty('--mx','0');ref.current?.style.setProperty('--my','0');}} aria-hidden="true"><div className="s-plane-field">{Array.from({length:5},(_,i)=><div className="s-plane" key={i} style={{'--i':i,'--shift':[16,6,0,6,16][i]+'%'}}><Picture src={src} eager={eager&&i===0}/></div>)}</div></div>;
}

export function HorizonMotion(){
 useEffect(()=>{const mm=gsap.matchMedia();
 mm.add('(prefers-reduced-motion: no-preference)',()=>{
  const scene=document.querySelector('.s-intro');
  if(scene){
   gsap.fromTo('.s-intro-title .s-line > span',{yPercent:105},{yPercent:0,duration:1.35,stagger:.13,ease:'power4.out'});
   gsap.fromTo('.s-intro-art .s-plane',{opacity:0,y:100},{opacity:1,y:0,duration:1.25,stagger:.08,ease:'power3.out'});
   if(matchMedia('(min-width: 901px)').matches){
    const tl=gsap.timeline({scrollTrigger:{trigger:scene,start:'top top',end:'bottom bottom',scrub:.6}});
    tl.to('.s-intro-art',{width:'100%',height:'88%',right:'0%',top:'12%',ease:'none'},0)
      .to('.s-intro-art .s-plane-field',{rotation:0,rotationY:0,ease:'none'},0)
      .to('.s-intro-art .s-plane',{clipPath:'inset(0% 0% 0% 0%)',rotateY:0,rotateZ:0,ease:'none'},0)
      .to('.s-intro-title',{y:-130,autoAlpha:0,ease:'none'},0)
      .to('.s-intro-topline',{autoAlpha:0},0)
      .to('.s-intro-bottom',{autoAlpha:0},0)
      .fromTo('.s-intro-end',{autoAlpha:0,y:35},{autoAlpha:1,y:0},.55);
   }
  }
  gsap.utils.toArray('.v3-site [data-s-reveal]').forEach(el=>gsap.fromTo(el,{y:42},{y:0,duration:1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 95%',once:true}}));
  gsap.utils.toArray('.v3-site .s-chapter-word').forEach(el=>gsap.fromTo(el,{xPercent:8},{xPercent:-8,ease:'none',scrollTrigger:{trigger:el,start:'top bottom',end:'bottom top',scrub:true}}));
  gsap.utils.toArray('.v3-site .s-image-reveal').forEach(el=>gsap.fromTo(el,{clipPath:'inset(12% 8% 12% 8%)'},{clipPath:'inset(0% 0% 0% 0%)',ease:'none',scrollTrigger:{trigger:el,start:'top 90%',end:'center center',scrub:.5}}));
 });return()=>mm.revert();},[]);return null;
}

function Intro(){
 const [scene,setScene]=useState(0);
 const scenes=[{name:'Океан',src:'home-hero.webp',region:'Приморский край'},{name:'Горы',src:'home-region-3.webp',region:'Камчатский край'},{name:'Культура',src:'hero-buryatia.webp',region:'Республика Бурятия'}];
 return <section className="s-intro" aria-labelledby="home-title"><div className="s-intro-sticky">
  <div className="s-intro-topline"><span>25 городов Дальнего Востока</span><span>Новый облик. Новый масштаб жизни.</span></div>
  <h1 className="s-intro-title" id="home-title"><span className="s-line"><span>Дальний.</span></span><span className="s-line"><span>Близкий.</span></span></h1>
  <Aperture className="s-intro-art" src={scenes[scene].src} eager/>
  <div className="s-intro-bottom"><a className="s-scroll" href="#scale"><span><ArrowDown size={22}/></span>Изменить масштаб</a><p>Большое будущее начинается<br/>с места, которое ты называешь домом.</p><div className="s-scene-switch" role="group" aria-label="Панорама Дальнего Востока">{scenes.map((s,i)=><button key={s.name} aria-pressed={scene===i} onClick={()=>setScene(i)}><span>{pad(i+1)}</span>{s.name}</button>)}</div></div>
  <div className="s-intro-end"><span>{scenes[scene].region}</span><p>От большого пространства —<br/>к жизни каждого.</p><HLink href="#scale">Узнать больше</HLink></div>
 </div></section>;
}

const scales=[{number:'11',label:'регионов',title:'У каждого места —\nсвой характер.',text:'От Байкала до Тихого океана. Сохраняем самобытность территорий и открываем новые возможности для их развития.',image:'home-region-3.webp',link:'География проекта',href:'#geography'},{number:'25',label:'городов',title:'У каждого города —\nсвоё будущее.',text:'Мастер-план связывает экономику, инфраструктуру и городскую среду в одну стратегию развития.',image:'home-hero.webp',link:'Как устроен мастер-план',href:siteHref('about')},{number:'4 млн+',label:'жителей',title:'В центре перемен —\nчеловек.',text:'Дом, работа, школа, прогулка у воды. Качество жизни складывается из простых вещей, которые должны быть рядом.',image:'editorial/visual-waterfront.webp',link:'Проекты для жизни',href:siteHref('projects')}];
function ScaleStory(){const[index,setIndex]=useState(0);const s=scales[index];return <section className="s-scale s-shell" id="scale"><Label number="01">Масштаб жизни</Label><div className="s-scale-layout"><div><h2>Большие перемены.<br/><em>Личный масштаб.</em></h2><div className="s-scale-tabs" role="group" aria-label="Масштаб проекта">{scales.map((x,i)=><button key={x.number} aria-pressed={index===i} onClick={()=>setIndex(i)}><strong>{x.number}</strong><span>{x.label}<ArrowUpRight size={17}/></span></button>)}</div><div className="s-scale-copy" key={index} aria-live="polite"><h3>{s.title}</h3><p>{s.text}</p><HLink href={s.href}>{s.link}</HLink></div></div><div className="s-scale-visual"><Picture key={s.image} src={s.image}/><span className="s-visual-index">0{index+1}<i>/ 03</i></span><span className="s-image-label">{index===2?'Образ городской среды':'Дальний Восток'}</span></div></div></section>;}

export function HorizonExplorer({items=regions}){
 const[active,setActive]=useState(items[0]?.id);const r=items.find(x=>x.id===active)||items[0];
 if(!r)return <p className="s-empty">Ничего не найдено. Попробуйте другой запрос.</p>;
 return <div className="s-explorer e-region-explorer"><div className="s-region-fan" role="group" aria-label="Выбрать регион">{items.map(item=><button key={item.id} aria-label={item.name} aria-pressed={r.id===item.id} onClick={()=>setActive(item.id)} onMouseEnter={()=>{if(matchMedia('(hover:hover)').matches)setActive(item.id);}} onFocus={()=>setActive(item.id)} style={{'--step':Math.abs(5-item.index)*11+'px'}}><Picture src={item.image}/><span className="s-fan-number">{pad(item.index)}</span><span className="s-fan-name">{regionShort[item.id]}</span></button>)}</div><div className="s-region-caption" aria-live="polite"><span className="s-region-counter">{pad(r.index)}<i>/ 11</i></span><div><p>{regionMood[r.id]}</p><h3>{r.name}</h3><small>{r.cities.filter(id=>parentTerritory(id)===id).map(id=>cityById[id]?.name).join(' · ')}</small></div><HLink href={siteHref(regionPath(r))}>Исследовать регион</HLink></div></div>;
}

const life=[{word:'Жить',image:'housing',title:'Место, куда хочется возвращаться.',text:'Новые кварталы, благоустроенные дворы и всё необходимое рядом.',href:siteHref('dvkvartal'),link:'Дальневосточный квартал'},{word:'Учиться',image:'school',title:'Место, где начинается большое.',text:'Школы, детские сады и образовательные пространства для нового поколения.',href:siteHref('projects','?q=школ'),link:'Проекты образования'},{word:'Отдыхать',image:'waterfront',title:'Место, где можно быть собой.',text:'Набережные, парки и прогулочные маршруты. Пространства для встреч и времени с близкими.',href:siteHref('projects','?q=набережн'),link:'Проекты набережных'}];
function Life(){const[index,setIndex]=useState(0);const item=life[index];return <section className="s-life" data-header-tone="dark" id="everyday"><div className="s-life-background"><Picture key={item.image} src={`editorial/visual-${item.image}.webp`}/></div><div className="s-shell s-life-inner"><Label number="03">Самое важное — рядом</Label><div className="s-life-tabs" role="group" aria-label="Жизнь в городе">{life.map((s,i)=><button aria-pressed={index===i} onClick={()=>setIndex(i)} key={s.word}><span>0{i+1}</span>{s.word}<ArrowUpRight size={44}/></button>)}</div><div className="s-life-copy" key={index} aria-live="polite"><h2>{item.title}</h2><p>{item.text}</p><HLink href={item.href}>{item.link}</HLink></div><span className="s-life-note">Образ городской среды</span></div></section>;}

function ProjectsRail(){const rail=useRef(null);const picks=['vladivostok','ulan-ude','petropavlovsk-kamchatsky','khabarovsk','yuzhno-sakhalinsk'].map(id=>projects.find(p=>p.city===id&&p.hasSourceImages)).filter(Boolean);const[at,setAt]=useState(0);const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;return <section className="s-projects" id="projects"><div className="s-shell"><Heading number="04" label="От идеи к месту" title={<>Будущее уже<br/>обретает форму.</>} href={siteHref('projects')} link={`Все ${projects.length} проектов`}/><div className="s-rail-controls"><span>Листайте проекты<ArrowRight size={18}/></span><div><button aria-label="Предыдущие проекты" disabled={at===0} onClick={()=>rail.current.scrollBy({left:-rail.current.clientWidth*.75,behavior:reduced()?'instant':'smooth'})}><ArrowLeft/></button><button aria-label="Следующие проекты" disabled={at===2} onClick={()=>rail.current.scrollBy({left:rail.current.clientWidth*.75,behavior:reduced()?'instant':'smooth'})}><ArrowRight/></button></div></div></div><div className="s-project-rail" ref={rail} tabIndex="0" role="region" aria-label="Избранные проекты" onScroll={e=>{const el=e.currentTarget;setAt(el.scrollLeft<5?0:el.scrollLeft+el.clientWidth>=el.scrollWidth-5?2:1);}}>{picks.map((p,i)=><a className="s-project-tile" key={p.id} href={projectHref(p)}><div className="s-project-photo"><Picture src={p.images[0]} alt={p.title}/><span>{pad(i+1)}</span><span className="s-project-arrow"><ArrowUpRight size={30}/></span></div><div className="s-project-meta"><span>{cityById[p.city]?.name}</span><span>Мастер-план</span></div><h3>{p.title}</h3></a>)}</div></section>;}

export function HorizonHome(){return <div className="s-home"><Intro/><ScaleStory/><section className="s-geography s-shell" id="geography"><Heading number="02" label="Увидеть ближе" title={<>Один Восток.<br/><em>11 характеров.</em></>} href={siteHref('regions')} link="Все территории"/><HorizonExplorer/></section><Life/><ProjectsRail/><section className="s-news s-shell" id="news"><Heading number="05" label="Перемены в движении" title={<>Что происходит<br/><em>прямо сейчас.</em></>} href={siteHref('news')} link="Все новости"/><div className="s-news-list">{news.slice(0,3).map((n,i)=><NewsLink key={n.id} post={n} className="s-news-row"><span>{pad(i+1)}</span><Picture src={n.image}/><div><time dateTime={n.date}>{dateText(n.date)}</time><h3>{n.title}</h3></div><ArrowUpRight size={32}/></NewsLink>)}</div></section><a className="s-map-callout" href={siteHref('map')} data-header-tone="dark"><div className="s-shell"><span>Следующий масштаб</span><strong>Каждое место.<br/>На одной карте.</strong><span className="s-map-circle"><ArrowUpRight strokeWidth={1}/></span></div></a></div>;}

export function HorizonPageHero({image,title,eyebrow,crumbs=[],children,compact=false,illustration=false}){return <section className={`s-page-hero ${image?'s-page-hero-image':''} ${compact?'s-page-compact':''}`}><div className="s-shell"><div className="s-page-meta"><a href={siteHref()}>Главная</a><span>/</span><span>{crumbs.at(-1)?.[0]||eyebrow}</span><span className="s-page-meta-end">25 / МАСШТАБ ЖИЗНИ</span></div><div className="s-page-hero-content"><div><Label number="↗">{eyebrow}</Label><h1>{title}</h1>{children}</div>{image?<div className="s-page-art"><Aperture src={image} eager/>{illustration&&<small>Иллюстрация</small>}</div>:<div className="s-page-emblem" aria-hidden="true">{Array.from({length:5},(_,i)=><i key={i} style={{'--i':i}}/>)}</div>}</div></div></section>;}

export function HorizonDirectory(){
 const[q,setQ]=useQueryState('q');const[view,setView]=useQueryState('view','regions');const cityView=view==='cities';
 const regionMatches=regions.filter(r=>normalize(r.name+' '+r.cities.map(id=>cityById[id].name).join(' ')).includes(normalize(q)));
 const cityMatches=cities.filter(c=>parentTerritory(c.id)===c.id).filter(c=>normalize(territoryName(c)+' '+regionById[c.region]?.name+' '+cities.filter(m=>parentTerritory(m.id)===c.id).map(m=>m.name).join(' ')).includes(normalize(q)));
 const href=c=>{const member=q.trim()?cities.find(m=>parentTerritory(m.id)===c.id&&normalize(m.name).includes(normalize(q))):null;return siteHref(cityPath(c),member&&member.id!==c.id?`?city=${member.id}#regions`:'');};
 return <div className="s-directory"><HorizonPageHero title={<>Место силы.<br/><em>Место жизни.</em></>} eyebrow="География перемен" crumbs={[["Регионы"]]} compact/><div className="s-shell"><div className="s-directory-tools"><div role="group" aria-label="Показать территории"><button aria-pressed={!cityView} onClick={()=>setView('regions')}>Регионы <sup>11</sup></button><button aria-pressed={cityView} onClick={()=>setView('cities')}>Города и агломерации <sup>{cities.filter(c=>parentTerritory(c.id)===c.id).length}</sup></button></div><label className="s-search"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Регион или город" aria-label="Найти регион или город"/>{q&&<button onClick={()=>setQ('')} aria-label="Очистить поиск"><X size={20}/></button>}</label></div><div className="s-result-count" aria-live="polite">{cityView?'Территорий':'Регионов'}: {cityView?cityMatches.length:regionMatches.length}</div>{cityView?<div className="s-city-grid">{cityMatches.map((c,i)=><a key={c.id} href={href(c)}><div><Picture src={c.image}/><span>{pad(i+1)}<ArrowUpRight size={24}/></span></div><small>{regionById[c.region].name}</small><h2>{territoryName(c)}</h2></a>)}</div>:<HorizonExplorer items={regionMatches}/>} {cityView&&!cityMatches.length&&<p className="s-empty">Ничего не найдено. Попробуйте другой запрос.</p>}</div></div>;
}

const aboutSteps=[{name:'Услышать',title:'Начать с человека.',text:'Мастер-планы создаются с учётом мнения жителей. Их потребности помогают определить общие цели развития и приоритеты городской среды.',image:'editorial/visual-waterfront.webp'},{name:'Связать',title:'Увидеть город целиком.',text:'Жильё, работа, образование, транспорт и отдых связаны между собой. Мастер-план объединяет их в общую стратегию пространственного и экономического развития.',image:'masterplan-editorial-v1.webp'},{name:'Создать',title:'Превратить идеи в места.',text:'Стратегия становится набором конкретных проектов. На портале можно изучить их параметры и расположение в мастер-планах городов.',image:'editorial/visual-school.webp'}];
export function HorizonAbout(){const[index,setIndex]=useState(0);const s=aboutSteps[index];return <div className="s-about"><HorizonPageHero image="masterplan-editorial-v1.webp" title={<>Не просто<br/>план. <em>Жизнь.</em></>} eyebrow="О проекте «25 городов»" crumbs={[["О проекте"]]} illustration><p>Новый облик Дальнего Востока начинается с того, что важно каждому.</p><HLink href="#approach">Как это работает</HLink></HorizonPageHero><section className="s-shell s-about-statement"><Label number="01">Смысл перемен</Label><h2 data-s-reveal>Город — больше,<br/>чем здания.<br/><em>Это возможности.</em></h2><div><p>Мастер-планы развития городов Дальнего Востока связывают перспективные отрасли экономики, рабочие места и городскую среду. Их цель — повысить качество жизни и раскрыть уникальные преимущества каждого места.</p><HLink href={siteHref('regions')}>Найти свой мастер-план</HLink></div></section><section className="s-approach" id="approach" data-header-tone="dark"><div className="s-shell"><Heading number="02" label="От человека к городу" title="Как устроен мастер-план"/><div className="s-approach-tabs" role="group" aria-label="Этапы мастер-плана">{aboutSteps.map((a,i)=><button aria-pressed={index===i} onClick={()=>setIndex(i)} key={a.name}><span>{pad(i+1)}</span>{a.name}<ArrowRight/></button>)}</div><div className="s-approach-body"><Picture src={s.image} key={s.image}/><div aria-live="polite" key={s.name}><h3>{s.title}</h3><p>{s.text}</p><HLink href={siteHref('projects')}>Посмотреть проекты</HLink></div></div></div></section><ScaleStory/><section className="s-shell s-about-faq"><Heading number="03" label="По существу" title="Что важно знать"/><div>{[['Чем мастер-план отличается от генерального плана?','Генеральный план отвечает на вопрос, что и где будет построено. Мастер-план объясняет, как и зачем развивается город: в контексте социальных, экономических и пространственных задач. Он описывает управленческие механизмы и источники финансирования.'],['Для кого создаются мастер-планы?','Мастер-план — публичный документ для жителей, бизнеса и власти. Он определяет общие принципы и стратегию развития города.'],['Где посмотреть проекты моего города?','Выберите регион, затем город или агломерацию. На странице территории доступны мастер-план, карта объектов и подробности проектов.']].map(([q,a],i)=><details key={q} name="about-questions"><summary><span>{pad(i+1)}</span><h3>{q}</h3><Plus/></summary><p>{a}</p></details>)}</div></section></div>;}

export function HorizonFooter(){return <footer className="s-footer"><div className="s-shell"><div className="s-footer-top"><Label number="25">Новый облик Дальнего Востока</Label><a href={siteHref('regions')}>Ближе<br/><em>к будущему.</em><ArrowUpRight strokeWidth={1}/></a></div><div className="s-footer-body"><div><a href={siteHref()}><img src={asset('logo-25-cities.svg')} alt="25 городов" width="150" height="36"/></a><p>Большое пространство.<br/>Личный масштаб.</p><a href="tel:88007075558">8 (800) 707-55-58</a></div><nav aria-label="Разделы в подвале">{[['about','О проекте'],['regions','Регионы'],['projects','Проекты'],['dvkvartal','ДВ Квартал'],['news','Новости'],['map','Карта проектов']].map(([p,n])=><a key={p} href={siteHref(p)}>{n}</a>)}</nav><nav className="s-footer-regions" aria-label="Регионы в подвале">{regions.map(r=><a key={r.id} href={siteHref(regionPath(r))}>{r.name}</a>)}</nav></div><div className="s-footer-bottom"><span>Корпорация развития Дальнего Востока и Арктики · 2026</span><a href={siteHref('sitemap')}>Карта сайта</a><a href="#top">Наверх ↑</a></div></div></footer>;}
