import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import Icon from '../components/Icon.jsx';
import {Search} from '../portal/icons.jsx';
import {media,normalize} from '../portal/data.js';
import {cityDirections,cityDirection,projectWord} from './city-atlas-data.js';
import {promoScenes} from '../content/promo-scenes.js';
import {illustratedCamera} from './illustrated-camera.js';
import './promo-atlas.css';
const pad=n=>String(n).padStart(2,'0');
export default function PromoAtlas({city,items}){
  const scene=promoScenes[city.id];
  const initial=new URLSearchParams(location.search).get('project');
  const directions=useMemo(()=>cityDirections.map(d=>({...d,count:items.filter(p=>cityDirection(p)===d.id).length})).filter(d=>d.count),[items]);
  const [selected,setSelected]=useState(items.some(p=>p.id===initial)?initial:''),[categoryId,setCategory]=useState(items.find(p=>p.id===initial)?cityDirection(items.find(p=>p.id===initial)):directions[0]?.id),[query,setQuery]=useState('');
  const [expanded,setExpanded]=useState(false),[imageIndex,setImageIndex]=useState(0),[copied,setCopied]=useState(false),[zoom,setZoom]=useState(1),[pan,setPan]=useState([0,0]),[failed,setFailed]=useState(false);
  const stage=useRef(null),viewport=useRef(null),panel=useRef(null),detail=useRef(null),expandButton=useRef(null),origin=useRef(null),drag=useRef(null);
  const [size,setSize]=useState({width:0,height:0});
  const points=items.map((p,i)=>({...p,number:i+1,category:cityDirection(p),anchor:scene.anchors[i]}));
  const project=points.find(p=>p.id===selected),active=directions.find(d=>d.id===categoryId)||directions[0];
  const shown=points.filter(p=>(query||p.category===active?.id)&&(!query||normalize(p.title).includes(normalize(query))));
  const camera=illustratedCamera(size.width,size.height,project?.anchor||scene.center||[66,48],!!project,zoom,pan,{left:size.width>=900?370:25,right:size.width-(project&&size.width>=900?390:25),top:85,bottom:size.height-55});
  const choose=id=>{origin.current=document.activeElement;setSelected(id);setImageIndex(0);setCopied(false);setCategory(points.find(p=>p.id===id).category);setPan([0,0]);setZoom(1);};
  const close=()=>{setSelected('');origin.current?.focus({preventScroll:true});};
  const changeCategory=id=>{setCategory(id);setQuery('');setSelected('');setPan([0,0]);setZoom(1);panel.current?.scrollTo({top:0});};
  useLayoutEffect(()=>{const n=viewport.current;const measure=()=>setSize({width:n.clientWidth,height:n.clientHeight});measure();const o=new ResizeObserver(measure);o.observe(n);return()=>o.disconnect();},[]);
  useEffect(()=>{const u=new URL(location.href);selected?u.searchParams.set('project',selected):u.searchParams.delete('project');history.replaceState(history.state,'',u);},[selected]);
  useEffect(()=>{if(project&&matchMedia('(max-width:899px)').matches)detail.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'nearest'});},[selected]);
  useEffect(()=>{const sync=()=>{const id=new URLSearchParams(location.search).get('project');const p=items.find(x=>x.id===id);setSelected(p?.id||'');if(p)setCategory(cityDirection(p));};window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync);},[items]);
  useEffect(()=>{if(!selected&&!expanded)return;const key=e=>{if(e.key==='Escape'){if(expanded){setExpanded(false);expandButton.current?.focus();}else close();}if(e.key==='Tab'&&expanded){const nodes=[...stage.current.querySelectorAll('button:not(:disabled),a[href],input,[tabindex="0"]')].filter(n=>n.getClientRects().length);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[selected,expanded]);
  useEffect(()=>{if(!expanded)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';expandButton.current?.focus();return()=>{document.body.style.overflow=before;};},[expanded]);
  const next=amount=>{const i=shown.findIndex(p=>p.id===selected);choose(shown[(i+amount+shown.length)%shown.length].id);};
  const share=async()=>{const u=new URL(location.href);u.hash='projects';try{await navigator.clipboard.writeText(u.href);setCopied(true);}catch{setCopied('fallback');}};
  const reset=()=>{setSelected('');setZoom(1);setPan([0,0]);};
  return <section id="projects" className="projects-section promo-atlas-section" aria-labelledby="projects-title"><div className="projects-overture"><div className="projects-intro shell"><div><span className="section-kicker">03 / Масштаб преобразований</span><h2 className="section-title" id="projects-title">Город меняется.<br/><span>Здесь и сейчас.</span></h2></div><div className="projects-total"><strong>{items.length}</strong><span>{projectWord(items.length)}<br/>в мастер-плане</span></div></div></div>
    <div ref={stage} className={`atlas promo-atlas ${expanded?'is-expanded':''} ${project?'has-selection':''}`} role={expanded?'dialog':'region'} aria-modal={expanded||undefined} aria-label={`Промокарта — ${city.name}`} style={{'--accent':active?.color||'#79dffa'}}>
      <div ref={viewport} className="promo-viewport" tabIndex={0} aria-label={`Карта — ${city.name}`} onKeyDown={e=>{if(e.target!==e.currentTarget)return;const moves={ArrowLeft:[60,0],ArrowRight:[-60,0],ArrowUp:[0,60],ArrowDown:[0,-60]};if(moves[e.key]){e.preventDefault();setPan(p=>p.map((v,i)=>v+moves[e.key][i]));}}} onPointerDown={e=>{if(e.button!==0||e.target.closest('button'))return;drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,pan};if(e.pointerType==='mouse'||expanded)e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d||(e.pointerType!=='mouse'&&!expanded))return;setPan([d.pan[0]+e.clientX-d.x,d.pan[1]+e.clientY-d.y]);}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
        <div className="promo-camera" style={size.width?{width:camera.width,height:camera.height,transform:`translate(${camera.x}px,${camera.y}px) scale(${camera.scale})`,'--map-scale':camera.scale}:undefined}><img src={media(scene.image)} alt={`Промокарта — ${city.name}`} className="atlas-terrain" loading="lazy" draggable="false" onError={()=>setFailed(true)}/><div className="promo-markers" aria-label="Объекты мастер-плана на карте">{points.map(p=><button key={p.id} style={{left:`${p.anchor[0]}%`,top:`${p.anchor[1]}%`,'--marker-color':cityDirections.find(d=>d.id===p.category).color}} className={`atlas-marker promo-marker ${p.category===categoryId?'is-in-category':'is-context'} ${selected===p.id?'is-active':''}`} aria-label={`Объект ${pad(p.number)}. ${p.title}`} aria-pressed={selected===p.id} onClick={()=>choose(p.id)}><span>{pad(p.number)}</span><span className="marker-tooltip">{p.title}</span></button>)}</div></div>
      </div><div className="atlas-vignette"/>{failed&&<div className="promo-image-error" role="status">Не удалось загрузить карту<button onClick={()=>location.reload()}>Обновить страницу</button></div>}
      <aside className="atlas-sidebar"><div className="atlas-sidebar-head"><span className="section-kicker">Атлас развития</span><h3>{city.name}</h3><span className="atlas-project-count">{items.length} {projectWord(items.length)} / {directions.length} направлений</span></div><div className="atlas-categories" aria-label="Направления развития">{directions.map(d=><button key={d.id} className={categoryId===d.id?'is-active':''} aria-pressed={categoryId===d.id} onClick={()=>changeCategory(d.id)}><Icon name={d.icon} size={21}/><span>{d.title}</span><small>{pad(d.count)}</small></button>)}</div><label className="promo-search"><Search size={17}/><input aria-label="Найти проект города" placeholder="Найти объект" value={query} onChange={e=>{setQuery(e.target.value);setSelected('');}}/>{query&&<button aria-label="Очистить поиск" onClick={()=>setQuery('')}><Icon name="close" size={16}/></button>}</label><div className="atlas-list-head"><span>{query?'Результаты поиска':active?.title}</span><span>{pad(shown.length)}</span></div><div ref={panel} className="atlas-project-list" aria-label="Проекты выбранного направления">{shown.map(p=><button key={p.id} className={`atlas-project ${selected===p.id?'is-active':''}`} aria-pressed={selected===p.id} onClick={()=>choose(p.id)}><span className="atlas-project-number">{pad(p.number)}</span><span>{p.title}</span><Icon name="arrow" size={17}/></button>)}{!shown.length&&<p className="promo-empty">Объекты не найдены. Попробуйте другое название.</p>}</div></aside>
      <div className="atlas-toolbar"><span className="atlas-mode">{items.length} {projectWord(items.length)} на карте</span><button aria-label="Приблизить карту" onClick={()=>setZoom(z=>Math.min(2.4,z+.2))}><Icon name="plus" size={22}/></button><button aria-label="Общий вид карты" onClick={reset}><Icon name="reset" size={22}/></button><button ref={expandButton} aria-label={expanded?'Закрыть полный экран':'Открыть карту на весь экран'} aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}><Icon name={expanded?'close':'expand'} size={23}/></button></div>
      {!project&&<div className="atlas-invitation"><span className="atlas-invitation-count">{pad(shown.length)}</span><div><span>проектов направления</span><h3>{active?.title}</h3><button disabled={!shown.length} onClick={()=>choose(shown[0].id)}>Исследовать<Icon name="arrow" size={22}/></button></div></div>}
      {project&&<article ref={detail} className="atlas-detail promo-detail" aria-labelledby="project-detail-title"><header className="atlas-detail-top"><span>{pad(project.number)} / {active?.title}</span><button aria-label="Закрыть карточку проекта" onClick={close}><Icon name="close" size={22}/></button></header><div className="project-detail-scroll">{project.images.length>0&&<figure className="project-cover"><img src={media(project.images[imageIndex])} alt={project.title}/>{project.images.length>1&&<div className="promo-gallery-controls"><button aria-label="Предыдущее изображение" onClick={()=>setImageIndex((imageIndex-1+project.images.length)%project.images.length)}><Icon name="left" size={18}/></button><span>{imageIndex+1}/{project.images.length}</span><button aria-label="Следующее изображение" onClick={()=>setImageIndex((imageIndex+1)%project.images.length)}><Icon name="right" size={18}/></button></div>}</figure>}<div className="project-body"><span className="project-tag">{city.name}</span><h3 id="project-detail-title">{project.title}</h3>{project.texts.map((t,i)=><p key={i} className="project-description">{t}</p>)}<dl className="promo-facts">{project.stats.map((s,i)=><div key={i}><dt>{s.label}</dt><dd>{s.value}</dd></div>)}</dl><button className="promo-share" onClick={share}><Icon name={copied===true?'check':'external'} size={18}/>{copied===true?'Ссылка скопирована':'Скопировать ссылку'}</button>{copied==='fallback'&&<input aria-label="Ссылка на объект" readOnly value={location.href} onFocus={e=>e.target.select()}/>}</div></div><footer className="atlas-detail-nav"><button aria-label="Предыдущий проект" disabled={shown.length<2} onClick={()=>next(-1)}><Icon name="left" size={20}/></button><span><strong>{pad(shown.findIndex(p=>p.id===selected)+1)}</strong> / {pad(shown.length)}</span><button aria-label="Следующий проект" disabled={shown.length<2} onClick={()=>next(1)}><Icon name="right" size={20}/></button></footer></article>}
      <div className="atlas-bottom"><span>{city.name}</span><span>Мастер-план развития</span></div>
    </div></section>;
}
