import {useEffect} from 'react';
import {cities,cityById,projects,media,regionPath,regionMood} from '../portal/data.js';
import {territoryName,parentTerritory} from '../content/territory-model.js';
import {siteHref} from '../site.js';
import Icon from '../components/Icon.jsx';
import Motion from '../components/Motion.jsx';
import './region-gateway.css';

const features=[['housing','Комфортные города','Жильё, общественные пространства и повседневные сервисы.'],['transport','Связанные территории','Транспорт и инфраструктура для удобных поездок.'],['economy','Новые возможности','Экономика, образование и места для работы.']];
const heroImage=r=>({primkrai:'hero-primorye.webp',buryatia:'hero-buryatia.webp'}[r.id]||r.image);
export default function RegionGateway({region:r}){
  const members=r.cities.filter(id=>parentTerritory(id)===id).map(id=>cityById[id]);
  useEffect(()=>{const id=new URLSearchParams(location.search).get('object');const target=id?document.getElementById(`project-${id}`):document.getElementById(location.hash.slice(1));if(target){let n=target;while(n){if(n.tagName==='DETAILS')n.open=true;n=n.parentElement;}requestAnimationFrame(()=>target.scrollIntoView({block:'start'}));}},[r.id]);
  return <div className="region-gateway">
    <section className="gateway-hero" aria-labelledby="hero-title">
      <img src={media(heroImage(r))} alt={r.name} fetchPriority="high"/>
      <div className="gateway-hero-content shell"><a className="gateway-back" href={siteHref('regions')}><Icon name="left" size={18}/>Все регионы</a><span className="section-kicker">Регион</span><h1 id="hero-title">{r.name}</h1><div className="gateway-stats">{r.stats.map(s=><div key={s.label}><small>{s.label.replace('км 2','км²')}</small><strong>{s.value.match(/^[\d\s.,]+/)?.[0].trim() || s.value}</strong><small className="gateway-stat-unit">{s.value.replace(/^[\d\s.,]+/,'').replace('км 2','км²')}</small></div>)}<div><small>Мастер-планы</small><strong>{members.length}</strong></div></div><a className="gateway-scroll" href="#masterplans">Выбрать территорию<Icon name="down" size={20}/></a></div>
    </section>
    <section className="gateway-territories" id="masterplans"><div className="shell"><div className="gateway-heading"><div><span className="section-kicker">Мастер-планы региона</span><h2>Мастер-планы.<br/><span>Будущее городов.</span></h2><p>Выберите город или агломерацию.</p></div><span>{String(members.length).padStart(2,'0')} / территорий</span></div><div className={`gateway-cards count-${members.length}`}>{members.map((c,i)=><a key={c.id} className="gateway-card" href={siteHref(c.id==='vladivostok'?'vladivostok':`cities/${c.id}`)}><img src={media(c.image)} alt="" loading="lazy"/><span className="gateway-card-number">{String(i+1).padStart(2,'0')}</span>{c.id==='vladivostok'&&<span className="gateway-card-count">3 территории</span>}<div><h3>{territoryName(c)}</h3>{c.id==='vladivostok'&&<p>Владивосток и остров Русский, Артём, Большой Камень</p>}<p>{c.mission}</p><span className="gateway-card-link">Открыть мастер-план<Icon name="arrow" size={21}/></span></div></a>)}</div></div></section>
    <section className="gateway-about"><div className="shell"><div className="gateway-about-lead"><div><span className="section-kicker">Характер региона</span><h2>{regionMood[r.id]}</h2><p>Мастер-планы объединяют развитие городской среды, инфраструктуры и экономики. Выберите территорию, чтобы увидеть проекты на её промокарте.</p></div><img src={media(`atlas-region-${r.id}.webp`)} alt={`Панорама — ${r.name}`} loading="lazy"/></div><h2 className="gateway-changes-title">Как изменится регион</h2><div className="gateway-features">{features.map(([icon,title,text])=><article key={icon}><Icon name={icon} size={28}/><h3>{title}</h3><p>{text}</p></article>)}</div><div className="gateway-programs" id="programs">{Object.entries(r.programs).map(([id,p])=><details id={`program-${id}`} key={id}><summary><span>{p.name}<small>{p.projects.length} объектов</small></span><Icon name="plus" size={22}/></summary><div>{p.projects.map(pid=>{const item=projects.find(x=>x.id===pid);return <details className="gateway-program-object" id={`project-${pid}`} key={pid}><summary>{item.title}<Icon name="plus" size={18}/></summary><div>{item.images[0]&&<img src={media(item.images[0])} alt={item.title} loading="lazy"/>}{item.texts.map((t,i)=><p key={i}>{t}</p>)}<dl>{item.stats.map((s,i)=><div key={i}><dt>{s.label}</dt><dd>{s.value}</dd></div>)}</dl></div></details>;})}</div></details>)}</div><a className="gateway-return" href="#masterplans">К мастер-планам<Icon name="up" size={18}/></a></div></section><Motion/>
  </div>;
}
