import {useEffect} from 'react';
import {cityById,projects,media,regionMood} from '../portal/data.js';
import {territoryName,parentTerritory} from '../content/territory-model.js';
import {siteHref} from '../site.js';
import {ArrowUpRight,ArrowLeft,Plus} from '../portal/icons.jsx';
import {Picture,SectionTitle,RoundArrow} from '../editorial/EditorialPages.jsx';
const heroImage=r=>({primkrai:'hero-primorye.webp',buryatia:'hero-buryatia.webp'}[r.id]||r.image);
export default function RegionGateway({region:r}){
 const members=r.cities.filter(id=>parentTerritory(id)===id).map(id=>cityById[id]);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('object');const target=id?document.getElementById(`project-${id}`):document.getElementById(location.hash.slice(1));if(target){let n=target;while(n){if(n.tagName==='DETAILS')n.open=true;n=n.parentElement;}requestAnimationFrame(()=>target.scrollIntoView({block:'start'}));}},[r.id]);
 return <div className="e-region-page e-shell region-gateway">
  <section aria-labelledby="hero-title"><a className="e-region-back" href={siteHref('regions')}><ArrowLeft size={16}/>Все регионы</a><div className="e-region-heading"><div><span className="e-label">Регион / {String(r.index).padStart(2,'0')}</span><h1 id="hero-title">{r.name}</h1></div><a className="e-link" href="#masterplans">Выбрать мастер-план<ArrowUpRight size={20}/></a></div><div className="e-region-lead"><div className="e-region-panorama"><Picture src={heroImage(r)} alt={r.name} eager data-parallax/><span>{regionMood[r.id]}</span></div><dl className="e-region-metrics">{r.stats.map(s=><div className="e-region-metric" key={s.label}><dt>{s.label.replace('км 2','км²')}</dt><dd><strong>{s.value.match(/^[\d\s.,]+/)?.[0].trim()||s.value}</strong><small>{s.value.replace(/^[\d\s.,]+/,'').replace('км 2','км²')}</small></dd></div>)}<div className="e-region-metric"><dt>Территории с мастер-планами</dt><dd><strong>{String(members.length).padStart(2,'0')}</strong></dd></div></dl></div></section>
  <section className="e-region-territories" id="masterplans"><SectionTitle number="01" label="Мастер-планы региона" title={<>Мастер-планы.<br/><em>Будущее городов.</em></>}/><div className="e-gateway-cards">{members.map((c,i)=><a key={c.id} className="e-gateway-card gateway-card" href={siteHref(c.id==='vladivostok'?'vladivostok':`cities/${c.id}`)}><div className="e-gateway-card-visual"><Picture src={c.image} alt={c.name}/><span>{String(i+1).padStart(2,'0')}{c.id==='vladivostok'?' / 3 территории':''}</span><RoundArrow/></div><h3>{territoryName(c)}</h3>{c.id==='vladivostok'&&<p>Владивосток и остров Русский, Артём, Большой Камень</p>}<p>{c.mission}</p><span className="e-link">Открыть мастер-план<ArrowUpRight size={20}/></span></a>)}</div></section>
  <section className="e-region-story" data-reveal><div><span className="e-label">Характер региона</span><h2>{regionMood[r.id]}</h2><p>Мастер-планы объединяют развитие городской среды, инфраструктуры и экономики. Выберите территорию, чтобы увидеть проекты на её промокарте.</p></div><Picture src={`atlas-region-${r.id}.webp`} alt={`Панорама — ${r.name}`}/></section>
  <section className="e-region-programs" id="programs"><span className="e-label">02 / Программы развития</span><h2>Как изменится регион</h2>{Object.entries(r.programs).map(([id,p])=><details id={`program-${id}`} key={id}><summary><span>{p.name}<small>{p.projects.length} объектов</small></span><Plus size={24}/></summary><div>{p.projects.map(pid=>{const item=projects.find(x=>x.id===pid);return <details className="gateway-program-object" id={`project-${pid}`} key={pid}><summary>{item.title}<Plus size={20}/></summary><div>{item.images[0]&&<Picture src={item.images[0]} alt={item.title}/ >}{item.texts.map((t,i)=><p key={i}>{t}</p>)}<dl>{item.stats.map((s,i)=><div key={i}><dt>{s.label}</dt><dd>{s.value}</dd></div>)}</dl></div></details>;})}</div></details>)}</section>
 </div>;
}
