import {useEffect,useState} from 'react';
import {cityById,projects,media,regionMood} from '../portal/data.js';
import {territoryName,parentTerritory} from '../content/territory-model.js';
import {siteHref} from '../site.js';
import {ArrowUpRight,ArrowLeft,Plus} from '../portal/icons.jsx';
import {Picture,HLink,Label,Heading,Aperture} from '../v3/HorizonPages.jsx';
const heroImage=r=>({primkrai:'hero-primorye.webp',buryatia:'hero-buryatia.webp'}[r.id]||r.image);
export default function RegionGateway({region:r}){
 const [selected,setSelected]=useState(0);
 const members=r.cities.filter(id=>parentTerritory(id)===id).map(id=>cityById[id]);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('object');const target=id?document.getElementById(`project-${id}`):document.getElementById(location.hash.slice(1));if(target){let n=target;while(n){if(n.tagName==='DETAILS')n.open=true;n=n.parentElement;}requestAnimationFrame(()=>target.scrollIntoView({block:'start'}));}},[r.id]);
 return <div className="s-region-page region-gateway">
  <section className="s-region-hero" aria-labelledby="hero-title"><div className="s-shell"><a className="s-region-back" href={siteHref('regions')}><ArrowLeft size={16}/>Все регионы</a><div className="s-region-heading"><Label number={String(r.index).padStart(2,'0')}>Дальний Восток / Регион</Label><div><h1 id="hero-title">{r.name}</h1><p>{regionMood[r.id]}</p><HLink href="#masterplans">Выбрать мастер-план</HLink></div></div></div><Aperture src={heroImage(r)} className="s-region-panorama" eager/></section>
  <div className="s-region-metrics" data-header-tone="dark"><dl className="s-shell">{r.stats.map(s=><div key={s.label}><dt>{s.label.replace('км 2','км²')}</dt><dd>{s.value.replace('км 2','км²')}</dd></div>)}<div><dt>Территории с мастер-планами</dt><dd>{String(members.length).padStart(2,'0')}</dd></div></dl></div>
  <section className="s-region-masterplans s-shell" id="masterplans"><Heading number="01" label="Мастер-планы региона" title={<>Разные города.<br/><em>Общее движение.</em></>}/><div className="s-territory-tabs" role="group" aria-label="Выбрать территорию">{members.map((c,i)=><button key={c.id} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span>{String(i+1).padStart(2,'0')}</span>{territoryName(c)}</button>)}</div><div className="s-territory-stage">{members.map((c,i)=><article key={c.id} hidden={selected!==i} className="s-territory-slide gateway-card"><div><Picture src={c.image} alt={c.name}/><span>{String(i+1).padStart(2,'0')} / {String(members.length).padStart(2,'0')}</span></div><div><Label number="↗">Территория развития</Label><h3>{territoryName(c)}</h3>{c.id==='vladivostok'&&<small>Владивосток и остров Русский, Артём, Большой Камень</small>}<p>{c.mission}</p><HLink href={siteHref(c.id==='vladivostok'?'vladivostok':`cities/${c.id}`)}>Открыть мастер-план</HLink></div></article>)}</div></section>
  <section className="s-region-story s-shell"><div><Label number="02">Характер места</Label><h2>{regionMood[r.id]}</h2><p>Мастер-планы объединяют развитие городской среды, инфраструктуры и экономики. У каждого города — свой характер и свой путь к будущему.</p></div><Picture src={`atlas-region-${r.id}.webp`} alt={`Панорама — ${r.name}`} className="s-image-reveal"/></section>
  <section className="e-region-programs s-shell" id="programs"><span className="e-label">03 / Программы развития</span><h2>Как изменится регион</h2>{Object.entries(r.programs).map(([id,p])=><details id={`program-${id}`} key={id}><summary><span>{p.name}<small>{p.projects.length} объектов</small></span><Plus size={24}/></summary><div>{p.projects.map(pid=>{const item=projects.find(x=>x.id===pid);return <details className="gateway-program-object" id={`project-${pid}`} key={pid}><summary>{item.title}<Plus size={20}/></summary><div>{item.images[0]&&<figure className="e-program-visual"><Picture src={item.images[0]} alt={item.title}/>{item.illustration&&<figcaption className="editorial-illustration">Иллюстрация</figcaption>}</figure>}{item.texts.map((t,i)=><p key={i}>{t}</p>)}<dl>{item.stats.map((s,i)=><div key={i}><dt>{s.label}</dt><dd>{s.value}</dd></div>)}</dl></div></details>;})}</div></details>)}</section>
 </div>;
}
