const asset = (name) => new URL(`../assets/${name}`, document.baseURI).href;

export const stages = [
  { id: "planned", label: "Запланировано", color: "#cdd3df" },
  { id: "prep", label: "Подготовительные работы", color: "#9da6b8" },
  { id: "design", label: "Проектирование", color: "#e68a3e" },
  { id: "build", label: "Строительство", color: "#4c83ea" },
  { id: "operation", label: "Введен в эксплуатацию", color: "#38b88a" },
];

export const industries = [
  { id: "housing", label: "Жилье и среда", icon: "⌂", color: "#f2b200" },
  { id: "transport", label: "Транспорт", icon: "▣", color: "#f26a00" },
  { id: "education", label: "Образование и наука", icon: "◇", color: "#08a8bd" },
  { id: "culture", label: "Культура и спорт", icon: "◈", color: "#8735c4" },
  { id: "health", label: "Здравоохранение", icon: "+", color: "#3779da" },
  { id: "infrastructure", label: "Инфраструктура", icon: "⚙", color: "#725047" },
  { id: "tourism", label: "Туризм", icon: "○", color: "#0e8d77" },
];

export const plans = [
  { id: "vladivostok", label: "Владивостокская агломерация", count: 277, center: [131.9203, 43.1869], zoom: 11.2 },
  { id: "bolshoy-kamen", label: "Большой Камень", count: 49, center: [132.3521, 43.1127], zoom: 11 },
  { id: "nakhodka", label: "Находка", count: 159, center: [132.8965, 42.824], zoom: 10.8 },
];

export const mapObjects = [
  {
    id: "port-terminal",
    planId: "vladivostok",
    title: "Специализированный контейнерный терминал",
    address: "Владивосток, район ул. Полтавская",
    description: "Портовый объект с реконструкцией подъездов, инженерных сетей и площадок хранения.",
    industryId: "transport",
    stageId: "build",
    deadline: "до 20 нояб. 2026",
    budget: "18.4 млрд ₽",
    area: "42 га",
    coordinates: [131.939, 43.136],
    image: asset("project-neftebaza.webp"),
    updatedAt: "2026-08-12",
  },
  {
    id: "kungasny-waterfront",
    planId: "vladivostok",
    title: "КРТ в районе мыса Кунгасного",
    address: "Владивосток, побережье Амурского залива",
    description: "Жилая и деловая застройка с общественными пространствами, набережной и сервисной инфраструктурой.",
    industryId: "housing",
    stageId: "design",
    deadline: "до 15 мар. 2027",
    budget: "130.5 млрд ₽",
    area: "94.22 га",
    coordinates: [131.879, 43.116],
    image: asset("project-kungasny.webp"),
    updatedAt: "2026-08-10",
  },
  {
    id: "russky-campus",
    planId: "vladivostok",
    title: "Научно-образовательный кластер на Русском острове",
    address: "о. Русский, кампусная зона",
    description: "Новые корпуса, общежития и лаборатории для образовательных программ агломерации.",
    industryId: "education",
    stageId: "operation",
    deadline: "введен",
    budget: "24.8 млрд ₽",
    area: "18 га",
    coordinates: [131.912, 43.027],
    image: asset("detail-vladivostok.webp"),
    updatedAt: "2026-08-08",
  },
  {
    id: "sport-harbor",
    planId: "vladivostok",
    title: "Спортивно-культурный центр бухты Патрокл",
    address: "Владивосток, район бухты Патрокл",
    description: "Общественный центр с залами, открытыми площадками и связью с прибрежным парком.",
    industryId: "culture",
    stageId: "build",
    deadline: "до 2 квартала 2027",
    budget: "7.6 млрд ₽",
    area: "7.4 га",
    coordinates: [131.975, 43.095],
    image: asset("project-ulyss.webp"),
    updatedAt: "2026-08-05",
  },
  {
    id: "clinic-network",
    planId: "vladivostok",
    title: "Сеть первичных медицинских пунктов",
    address: "Владивосток, несколько районов",
    description: "Модульные пункты приема и диагностики рядом с жилыми кварталами.",
    industryId: "health",
    stageId: "prep",
    deadline: "до 4 квартала 2026",
    budget: "2.1 млрд ₽",
    area: "12 объектов",
    coordinates: [131.944, 43.178],
    image: asset("mission-city.webp"),
    updatedAt: "2026-08-01",
  },
  {
    id: "arterial-road",
    planId: "vladivostok",
    title: "Связующая магистраль северных районов",
    address: "Владивосток, северный планировочный район",
    description: "Реконструкция уличной сети, новые остановки и выделенные транспортные связи.",
    industryId: "transport",
    stageId: "planned",
    deadline: "после 2027",
    budget: "11.2 млрд ₽",
    area: "16 км",
    coordinates: [131.973, 43.24],
    image: asset("city-vladivostok.webp"),
    updatedAt: "2026-07-29",
  },
  {
    id: "utilities-ring",
    planId: "vladivostok",
    title: "Инженерное кольцо агломерации",
    address: "Владивосток, Артем, Надеждинский район",
    description: "Магистральные сети водоснабжения, теплоснабжения и резервные мощности.",
    industryId: "infrastructure",
    stageId: "build",
    deadline: "до 2028",
    budget: "31.9 млрд ₽",
    area: "48 км сетей",
    coordinates: [132.055, 43.298],
    image: asset("mission-map.webp"),
    updatedAt: "2026-07-21",
  },
  {
    id: "artem-hub",
    planId: "vladivostok",
    title: "Транспортно-логистический узел Артема",
    address: "Артем, аэропортовая зона",
    description: "Связка аэропорта, складской инфраструктуры и пригородного общественного транспорта.",
    industryId: "transport",
    stageId: "operation",
    deadline: "введен",
    budget: "9.7 млрд ₽",
    area: "21 га",
    coordinates: [132.168, 43.354],
    image: asset("city-artem.webp"),
    updatedAt: "2026-07-18",
  },
  {
    id: "coastal-park",
    planId: "vladivostok",
    title: "Прибрежный рекреационный маршрут",
    address: "Амурский залив, городская береговая линия",
    description: "Связанные прогулочные зоны, веломаршрут и точки доступа к воде.",
    industryId: "tourism",
    stageId: "design",
    deadline: "до 2027",
    budget: "4.3 млрд ₽",
    area: "22 км",
    coordinates: [131.858, 43.167],
    image: asset("project-firsova.webp"),
    updatedAt: "2026-07-12",
  },
  {
    id: "bolshoy-yard",
    planId: "bolshoy-kamen",
    title: "Обновление производственной территории",
    address: "Большой Камень, промышленная зона",
    description: "Площадки сервисных производств и новая инженерная подготовка территории.",
    industryId: "infrastructure",
    stageId: "prep",
    deadline: "до 2027",
    budget: "6.8 млрд ₽",
    area: "14 га",
    coordinates: [132.361, 43.118],
    image: asset("city-bolshoy-kamen.webp"),
    updatedAt: "2026-07-08",
  },
  {
    id: "nakhodka-boulevard",
    planId: "nakhodka",
    title: "Городской бульвар Находки",
    address: "Находка, центральная планировочная ось",
    description: "Пешеходная ось, общественные первые этажи и благоустройство транспортных пересадок.",
    industryId: "housing",
    stageId: "planned",
    deadline: "после 2027",
    budget: "5.2 млрд ₽",
    area: "6.5 км",
    coordinates: [132.895, 42.814],
    image: asset("city-vladivostok.webp"),
    updatedAt: "2026-07-03",
  },
];

export const influencePolygon = [
  [131.77, 43.08],
  [131.88, 43.01],
  [132.09, 43.08],
  [132.12, 43.27],
  [131.97, 43.35],
  [131.79, 43.25],
  [131.77, 43.08],
];
