import {useState} from 'react';
import {ArrowUpRight,ArrowDown,Search,X} from '../portal/icons.jsx';
import {regions,cities,projects,quarter,news,regionById,cityById,regionPath,cityPath,projectHref,media,dateText,normalize,regionShort,regionMood} from '../portal/data.js';
import {siteHref} from '../site.js';
import {territoryName,parentTerritory} from '../content/territory-model.js';
import {NewsLink} from '../portal/NewsModal.jsx';
import {useQueryState} from '../portal/interactions.jsx';
const pad=n=>String(n).padStart(2,'0');
export const Picture=({src,alt='',className='',eager=false,...props})=><img src={media(src)} alt={alt} className={className} loading={eager?'eager':'lazy'} decoding="async" {...props}/>;
export const RoundArrow=({down=false})=><span className="e-round-arrow">{down?<ArrowDown size={22}/>:<ArrowUpRight size={22}/>}</span>;
export function SectionTitle({number,label,title,href,link}){return <div className="e-section-title" data-reveal><div><span className="e-label"><span>{number}</span>{label}</span><h2>{title}</h2></div>{href&&<a className="e-link" href={href}>{link}<ArrowUpRight size={20}/></a>}</div>;}
function CityFinder(){
 const [id,setId]=useState('');
 return <form className="e-city-finder" onSubmit={e=>{e.preventDefault();if(id)location.assign(siteHref(cityPath(cityById[id]),`?city=${id}#regions`));}}><div><span className="e-label">Мастер-план рядом с вами</span><h2>Будущее вашего города</h2></div><label><span className="visually-hidden">Выберите город</span><select value={id} onChange={e=>setId(e.target.value)} aria-label="Выберите город"><option value="">Выберите город</option>{regions.map(r=><optgroup key={r.id} label={r.name}>{cities.filter(c=>c.region===r.id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</optgroup>)}</select></label><button type="submit" disabled={!id}>Открыть мастер-план<ArrowUpRight size={20}/></button></form>;
}
export function RegionExplorer({items=regions,compact=false}){
 const [active,setActive]=useState(items[0]?.id);const r=items.find(x=>x.id===active)||items[0];
 if(!r)return <p className="e-empty">Ничего не найдено. Попробуйте другой запрос.</p>;
 return <div className={`e-region-explorer ${compact?'is-compact':''}`}>
  <a className="e-region-preview" href={siteHref(regionPath(r))} aria-label={`Открыть регион: ${r.name}`}><Picture key={r.id} src={r.image} alt={r.name}/><div className="e-region-photo-top"><span>География развития</span><span>{pad(r.index)} / 11</span></div><div className="e-region-preview-copy"><span className="e-label">{regionMood[r.id]}</span><h3>{r.name}</h3><p>{r.cities.filter(id=>parentTerritory(id)===id).map(id=>cityById[id]?.name).join(' · ')}</p><span className="e-link">Изучить регион<ArrowUpRight size={22}/></span></div></a>
  <nav className="e-region-index" aria-label="Регионы Дальнего Востока">{items.map(item=><a key={item.id} className={`e-region-row ${r.id===item.id?'is-active':''}`} href={siteHref(regionPath(item))} onMouseEnter={()=>setActive(item.id)} onFocus={()=>setActive(item.id)}><span>{pad(item.index)}</span><strong>{item.name}</strong><ArrowUpRight size={21}/></a>)}</nav>
 </div>;
}
function FeatureProjects(){
 const picks=['vladivostok','ulan-ude','petropavlovsk-kamchatsky'].map(id=>projects.find(p=>p.city===id&&p.images.length)).filter(Boolean);
 const [selected,setSelected]=useState(0);const p=picks[selected];
 return <section className="e-project-feature" id="projects"><div className="e-shell"><SectionTitle number="02" label="От замысла к городу" title={<>Будущее обретает<br/><em>очертания.</em></>} href={siteHref('projects')} link="Все проекты"/>
  <div className="e-feature-layout"><a className="e-feature-picture" href={projectHref(p)} aria-label={p.title}><Picture key={p.id} src={p.images[0]} alt={p.title}/><span className="e-feature-caption">{cityById[p.city]?.name}<ArrowUpRight size={22}/></span></a>
  <div className="e-feature-info"><span className="e-label">Мастер-план / {regionShort[p.region]}</span><h3 key={p.id}>{p.title}</h3>{p.stats.length>0&&<dl>{p.stats.slice(0,2).map((s,i)=><div key={i}><dt>{s.label}</dt><dd>{s.value}</dd></div>)}</dl>}<a className="e-link" href={projectHref(p)}>О проекте<ArrowUpRight size={20}/></a><div className="e-feature-pagination" role="group" aria-label="Избранные проекты">{picks.map((item,i)=><button key={item.id} aria-label={`Показать проект: ${item.title}`} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span>{pad(i+1)}</span><span className="e-feature-progress"/></button>)}</div></div></div>
  <a className="e-map-link" href={siteHref('map')}><span>Города, направления развития и объекты мастер-планов</span><strong>Все перемены — на одной карте</strong><RoundArrow/></a>
 </div></section>;
}
export function EditorialHome(){
 return <div className="e-home">
  <section className="e-hero e-shell"><div className="e-hero-top"><span className="e-label">Стратегические мастер-планы</span><span>От Байкала до Тихого океана</span></div><div className="e-hero-heading"><h1><span>Новый облик</span><span>Дальнего Востока<span className="e-dot">.</span></span></h1><a href="#regions" className="e-hero-explore" aria-label="Исследовать регионы"><ArrowDown size={32} strokeWidth={1}/></a></div><div className="e-hero-panorama"><Picture src="home-hero.webp" alt="Русский мост во Владивостоке" eager data-parallax/><div className="e-photo-caption"><span>Города для жизни,<br/>работы и будущего.</span><span>01 / Приморский край<br/>Русский мост</span></div><div className="e-hero-stat"><strong>25</strong><span>городов.<br/>Одно большое будущее.</span></div></div><CityFinder/></section>
  <section className="e-intro e-shell" id="about" data-reveal><span className="e-label">В центре — человек</span><div><h2>Перемены начинаются<br/>с <em>мастер-плана.</em></h2><p>Мастер-планы создаются с учётом мнения жителей. Они определяют принципы развития городов, приоритетные проекты и источники их финансирования.</p><a className="e-link" href={siteHref('about')}>Как устроен проект<ArrowUpRight size={20}/></a></div><div className="e-intro-fact"><strong>4<span>млн+</span></strong><p>жителей —<br/>в центре преобразований</p></div></section>
  <section className="e-geography e-shell" id="regions"><SectionTitle number="01" label="География развития" title={<>Разные города.<br/><em>Общие возможности.</em></>} href={siteHref('regions')} link="Регионы и города"/><RegionExplorer/></section>
  <FeatureProjects/>
  <section className="e-life e-shell" data-reveal><div className="e-life-copy"><span className="e-label">Возможности для жизни</span><h2>Комфортная<br/><em>среда.</em></h2><p>Реализация мастер-планов позволит улучшить условия жизни более чем 4 миллионов дальневосточников.</p><a className="e-link" href={siteHref('about')}>О мастер-планах<ArrowUpRight size={20}/></a></div><div className="e-life-picture"><Picture src="masterplan-editorial-v1.webp" alt="Городская набережная и общественные пространства" data-parallax/><span className="e-picture-note">В центре — человек</span></div></section>
  <section className="e-housing e-shell" id="quarter" data-reveal><a className="e-housing-picture" href={siteHref('dvkvartal')} aria-label="Дальневосточный квартал"><Picture src={quarter.projects[0].image} alt="Визуализация жилищного проекта в Амурской области"/><span className="e-housing-count">{pad(quarter.projects.length)}<small>проектов</small></span></a><div className="e-housing-copy"><span className="e-label">03 / Дальневосточный квартал</span><h2>Дом начинается<br/><em>с города.</em></h2><p>Современное жильё, школы, детские сады и общественные пространства рядом с домом.</p><a className="e-solid-link" href={siteHref('dvkvartal')}>О программе<ArrowUpRight size={22}/></a></div></section>
  <section className="e-news e-shell" id="news"><SectionTitle number="04" label="Новости проекта" title={<>Города меняются.<br/><em>Следите за событиями.</em></>} href={siteHref('news')} link="Все новости"/><div className="e-news-grid">{news.slice(0,3).map(n=><NewsLink key={n.id} post={n} className="e-news-card"><div className="e-news-picture"><Picture src={n.image} alt=""/><RoundArrow/></div><time dateTime={n.date}>{dateText(n.date)}</time><h3>{n.title}</h3></NewsLink>)}</div></section>
 </div>;
}
export function EditorialRegions(){
 const[q,setQ]=useQueryState('q');const[view,setView]=useQueryState('view','regions');
 const territoryCities=cities.filter(c=>parentTerritory(c.id)===c.id);
 const regionMatches=regions.filter(r=>normalize(r.name+' '+r.cities.map(id=>cityById[id].name).join(' ')).includes(normalize(q)));
 const cityMatches=territoryCities.filter(c=>normalize(territoryName(c)+' '+regionById[c.region]?.name+' '+cities.filter(member=>parentTerritory(member.id)===c.id).map(member=>member.name).join(' ')).includes(normalize(q)));
 const directoryCityHref=c=>{const member=q.trim()?cities.find(member=>parentTerritory(member.id)===c.id&&normalize(member.name).includes(normalize(q))):null;return siteHref(cityPath(c),member&&member.id!==c.id?`?city=${member.id}#regions`:'');};
 const cityView=view==='cities';
 return <div className="e-directory e-shell"><div className="e-page-heading"><span className="e-label">География развития / 11 регионов</span><h1>Один Дальний Восток.<br/><em>11 характеров.</em></h1><p>Выберите регион, город или агломерацию.</p></div><div className="e-directory-tools"><div role="group" aria-label="Показать территории"><button aria-pressed={!cityView} onClick={()=>setView('regions')}>Регионы<span>11</span></button><button aria-pressed={cityView} onClick={()=>setView('cities')}>Города и агломерации<span>{territoryCities.length}</span></button></div><label className="e-search"><Search size={20}/><input aria-label="Найти регион или город" placeholder="Регион или город" value={q} onChange={e=>setQ(e.target.value)}/>{q&&<button onClick={()=>setQ('')} aria-label="Очистить поиск"><X size={18}/></button>}</label></div><div className="e-directory-count" aria-live="polite">{cityView?'Территорий':'Регионов'}: {cityView?cityMatches.length:regionMatches.length}{q&&<button onClick={()=>setQ('')}>Сбросить поиск</button>}</div>{cityView?<div className="e-city-directory">{cityMatches.map((c,i)=><a href={directoryCityHref(c)} key={c.id}><div><Picture src={c.image} alt={c.name}/><span>{pad(i+1)}</span><RoundArrow/></div><small>{regionById[c.region].name}</small><h2>{territoryName(c)}</h2><p>{c.mission}</p></a>)}</div>:<RegionExplorer items={regionMatches}/>}{cityView&&!cityMatches.length&&<p className="e-empty">Ничего не найдено. Попробуйте другой запрос.</p>}</div>;
}
