// Generated from the client workbook, sheet ВЫБРАНО.
// Anchors are illustrative composition coordinates, never cadastral locations.
export const projectCategories = [
  {
    id: "housing",
    label: "Жильё и деловая застройка",
    shortLabel: "Жильё и бизнес",
    icon: "icon-category-housing.svg",
    color: "#7de0fb",
  },
  {
    id: "social",
    label: "Социальная инфраструктура",
    shortLabel: "Социальная среда",
    icon: "icon-category-social.svg",
    color: "#9ad6ff",
  },
  {
    id: "transport",
    label: "Транспорт и мобильность",
    shortLabel: "Транспорт",
    icon: "icon-category-transport.svg",
    color: "#ffc894",
  },
  {
    id: "engineering",
    label: "Инженерная инфраструктура",
    shortLabel: "Инфраструктура",
    icon: "icon-category-engineering.svg",
    color: "#9fc1ff",
  },
  {
    id: "ecology",
    label: "Рекреация и экология",
    shortLabel: "Парки и экология",
    icon: "icon-category-ecology.svg",
    color: "#abebbe",
  },
  {
    id: "tourism",
    label: "Туризм",
    shortLabel: "Туризм",
    icon: "icon-category-tourism.svg",
    color: "#ecdfa9",
  },
  {
    id: "economy",
    label: "Экономика и логистика",
    shortLabel: "Экономика",
    icon: "icon-mission-industry.svg",
    color: "#bcbcff",
  },
];

export const selectedProjects = [
  {
    id: "project-01",
    number: 1,
    category: "housing",
    title: "Комплексное развитие территории в районе мыса Кунгасного",
    shortTitle: "Мыс Кунгасного",
    group: "КРТ",
    area: "Владивосток",
    scope: "project",
    anchor: [56, 23],
    image: "project-kungasny.webp",
    sourceRow: 3,
  },
  {
    id: "project-02",
    number: 2,
    category: "housing",
    title: "Комплексное развитие территории в районе мыса Фирсова",
    shortTitle: "Мыс Фирсова",
    group: "КРТ",
    area: "Владивосток",
    scope: "project",
    anchor: [61, 16],
    image: "project-firsova.webp",
    sourceRow: 4,
  },
  {
    id: "project-03",
    number: 3,
    category: "social",
    title: "ИНТЦ «Русский»",
    shortTitle: "ИНТЦ «Русский»",
    group: "Высшее и среднее профессиональное образование",
    area: "Остров Русский",
    scope: "project",
    anchor: [63, 65],
    image: null,
    sourceRow: 6,
  },
  {
    id: "project-04",
    number: 4,
    category: "social",
    title: "Вторая очередь ДВФУ",
    shortTitle: "Вторая очередь ДВФУ",
    group: "Высшее и среднее профессиональное образование",
    area: "Остров Русский",
    scope: "project",
    anchor: [66, 59],
    image: null,
    sourceRow: 7,
  },
  {
    id: "project-05",
    number: 5,
    category: "social",
    title: "Капремонт фасада и кровли ОКС «Дом доходный Демби А. Г.»",
    shortTitle: "Дом доходный Демби",
    group: "Культура",
    area: "Владивосток",
    scope: "project",
    anchor: [53, 31],
    image: null,
    sourceRow: 8,
  },
  {
    id: "project-06",
    number: 6,
    category: "social",
    title: "Керлинг-центр",
    shortTitle: "Керлинг-центр",
    group: "Спорт",
    area: "Владивосток",
    scope: "project",
    anchor: null,
    image: null,
    sourceRow: 9,
  },
  {
    id: "project-07",
    number: 7,
    category: "social",
    title: "Более 100 городских объектов спортивной инфраструктуры",
    shortTitle: "Городская спортивная инфраструктура",
    group: "Спорт",
    area: "Владивосток",
    scope: "program",
    anchor: null,
    image: null,
    sourceRow: 10,
  },
  {
    id: "project-08",
    number: 8,
    category: "social",
    title: "Строительство 9 поликлиник",
    shortTitle: "9 новых поликлиник",
    group: "Здравоохранение",
    area: "Владивосток",
    scope: "program",
    anchor: null,
    image: null,
    sourceRow: 11,
  },
  {
    id: "project-09",
    number: 9,
    category: "transport",
    title: "Обновление троллейбусного парка, 20 ед. (первая очередь)",
    shortTitle: "Обновление троллейбусного парка",
    group: "Городской общественный транспорт",
    area: "Владивосток",
    scope: "program",
    anchor: null,
    image: null,
    sourceRow: 13,
  },
  {
    id: "project-10",
    number: 10,
    category: "transport",
    title: "Реконструкция пирса на о. Попова (пролив Старка)",
    shortTitle: "Пирс на острове Попова",
    group: "Морское сообщение",
    area: "Остров Попова",
    scope: "project",
    anchor: null,
    image: null,
    sourceRow: 14,
  },
  {
    id: "project-11",
    number: 11,
    category: "transport",
    title: "Реконструкция Рудневского моста",
    shortTitle: "Рудневский мост",
    group: "Улично-дорожная сеть до 2030 г.",
    area: "Владивосток",
    scope: "project",
    anchor: [65, 18],
    image: null,
    sourceRow: 15,
  },
  {
    id: "project-12",
    number: 12,
    category: "transport",
    title:
      "Прочие мероприятия по реконструкции и строительству улично-дорожной сети",
    shortTitle: "Развитие улично-дорожной сети",
    group: "Улично-дорожная сеть до 2030 г.",
    area: "Владивосток",
    scope: "program",
    anchor: null,
    image: null,
    sourceRow: 16,
  },
  {
    id: "project-13",
    number: 13,
    category: "transport",
    title: "Рекреационный велосипедный маршрут на о. Русский",
    shortTitle: "Веломаршрут на острове Русский",
    group: "Пешеходная инфраструктура и микромобильность",
    area: "Остров Русский",
    scope: "area",
    anchor: null,
    image: null,
    sourceRow: 17,
  },
  {
    id: "project-14",
    number: 14,
    category: "engineering",
    title: "Развитие системы электроснабжения",
    shortTitle: "Электроснабжение",
    group: "Развитие инженерной инфраструктуры",
    area: "Владивосток",
    scope: "program",
    anchor: null,
    image: null,
    sourceRow: 19,
  },
  {
    id: "project-15",
    number: 15,
    category: "engineering",
    title: "Развитие системы теплоснабжения",
    shortTitle: "Теплоснабжение",
    group: "Развитие инженерной инфраструктуры",
    area: "Владивосток",
    scope: "program",
    anchor: null,
    image: null,
    sourceRow: 20,
  },
  {
    id: "project-16",
    number: 16,
    category: "engineering",
    title: "Развитие систем водоснабжения",
    shortTitle: "Водоснабжение",
    group: "Развитие инженерной инфраструктуры",
    area: "Владивосток",
    scope: "program",
    anchor: null,
    image: null,
    sourceRow: 21,
  },
  {
    id: "project-17",
    number: 17,
    category: "engineering",
    title: "Развитие систем водоотведения",
    shortTitle: "Водоотведение",
    group: "Развитие инженерной инфраструктуры",
    area: "Владивосток",
    scope: "program",
    anchor: null,
    image: null,
    sourceRow: 22,
  },
  {
    id: "project-18",
    number: 18,
    category: "ecology",
    title: "Набережная вдоль Амурского залива",
    shortTitle: "Набережная Амурского залива",
    group: "Благоустройство рекреационных пространств",
    area: "Владивосток",
    scope: "area",
    anchor: [54, 25],
    image: null,
    sourceRow: 24,
  },
  {
    id: "project-19",
    number: 19,
    category: "ecology",
    title: "Парк Минного городка",
    shortTitle: "Парк Минного городка",
    group: "Благоустройство рекреационных пространств",
    area: "Владивосток",
    scope: "project",
    anchor: [72, 24],
    image: null,
    sourceRow: 25,
  },
  {
    id: "project-20",
    number: 20,
    category: "ecology",
    title: "Площадь Борцов Революции",
    shortTitle: "Площадь Борцов Революции",
    group: "Благоустройство рекреационных пространств",
    area: "Владивосток",
    scope: "project",
    anchor: [57, 31],
    image: null,
    sourceRow: 26,
  },
  {
    id: "project-21",
    number: 21,
    category: "ecology",
    title: "Дноуглубление р. Объяснения и очистка донных отложений",
    shortTitle: "Река Объяснения",
    group: "Ревитализация бухты Золотой Рог, поднятие затонувших кораблей",
    area: "Владивосток",
    scope: "project",
    anchor: [67, 30],
    image: null,
    sourceRow: 27,
  },
  {
    id: "project-22",
    number: 22,
    category: "ecology",
    title:
      "Межмуниципальный объект утилизации органической фракции (компостирование)",
    shortTitle: "Утилизация органической фракции",
    group: "Обращение с ТКО",
    area: "Владивосток",
    scope: "project",
    anchor: null,
    image: null,
    sourceRow: 28,
  },
  {
    id: "project-23",
    number: 23,
    category: "tourism",
    title: "Ревитализация дворов Миллионки",
    shortTitle: "Дворы Миллионки",
    group: "Развитие туристической инфраструктуры",
    area: "Владивосток",
    scope: "project",
    anchor: [53, 29],
    image: null,
    sourceRow: 30,
  },
  {
    id: "project-24",
    number: 24,
    category: "tourism",
    title: "Реставрация объектов музея-заповедника «Владивостокская крепость»",
    shortTitle: "Владивостокская крепость",
    group: "Развитие туристической инфраструктуры",
    area: "Владивосток",
    scope: "program",
    anchor: null,
    image: null,
    sourceRow: 31,
  },
  {
    id: "project-25",
    number: 25,
    category: "tourism",
    title: "Благоустройство пляжей на о. Русский",
    shortTitle: "Пляжи острова Русский",
    group: "Развитие туристической инфраструктуры",
    area: "Остров Русский",
    scope: "area",
    anchor: null,
    image: null,
    sourceRow: 32,
  },
  {
    id: "project-26",
    number: 26,
    category: "tourism",
    title: "Создание культурно-познавательных маршрутов",
    shortTitle: "Культурно-познавательные маршруты",
    group: "Развитие туристической инфраструктуры",
    area: "Владивосток",
    scope: "program",
    anchor: null,
    image: null,
    sourceRow: 33,
  },
  {
    id: "project-27",
    number: 27,
    category: "economy",
    title: "Агрологистический комплекс и рыбная биржа",
    shortTitle: "Агрологистический комплекс и рыбная биржа",
    group: "Развитие экономики и логистики",
    area: "Владивосток",
    scope: "project",
    anchor: null,
    image: null,
    sourceRow: 35,
  },
];
